// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfy5cLY3b2L5vP1HPjOQ7F4exRuu4s78g',
    appId: '1:236710668549:web:a563b53c52d04a81afef6c',
    messagingSenderId: '236710668549',
    projectId: 'auth-e9db6',
    authDomain: 'auth-e9db6.firebaseapp.com',
    storageBucket: 'auth-e9db6.appspot.com',
    measurementId: 'G-835HVT35MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfCfL6Bf8z44eEodDLzV5P_34JX9Xk7KM',
    appId: '1:236710668549:android:89e7de900ab8f759afef6c',
    messagingSenderId: '236710668549',
    projectId: 'auth-e9db6',
    storageBucket: 'auth-e9db6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLlYtJ1yx1ALPceUPNuQ4BUnfQgrHU_Y',
    appId: '1:236710668549:ios:0183f57450a3fffdafef6c',
    messagingSenderId: '236710668549',
    projectId: 'auth-e9db6',
    storageBucket: 'auth-e9db6.appspot.com',
    iosClientId:
        '236710668549-t72vio87cbnu6570ud4s0j0mkt9hk4r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcLlYtJ1yx1ALPceUPNuQ4BUnfQgrHU_Y',
    appId: '1:236710668549:ios:0183f57450a3fffdafef6c',
    messagingSenderId: '236710668549',
    projectId: 'auth-e9db6',
    storageBucket: 'auth-e9db6.appspot.com',
    iosClientId:
        '236710668549-t72vio87cbnu6570ud4s0j0mkt9hk4r5.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
